Repository labs14-stampd/backend, pull requests merged in 2019-08, with the labels that each got.

#7 Merge initial Auth0 Setup into Development
  api/auth.js
  api/middleware.js
  api/tokenService.js
  database/migrations/20190730092331_users.js
  database/seeds/002-users.js
  package.json
  schema/mutation.js
  schema/types.js
  yarn.lock
Labels: enhancement

#9 Fix addUser Login Bug
  api/auth.js
  api/middleware.js
  api/tokenService.js
  database/migrations/20190730092331_users.js
  database/seeds/002-users.js
  package.json
  schema/mutation.js
  schema/query.js
  schema/types.js
  yarn.lock
Labels: bug, enhancement

#10 Merge in
  api/getLoginStatus.js
  database/migrations/20190730092331_users.js
  database/seeds/002-users.js
  package.json
  schema/mutation.js
  schema/types.js
  yarn.lock
Labels: enhancement

#11 Add Login Processes (Auth0/JSON Web Tokens)
  api/getLoginStatus.js
  database/migrations/20190730092331_users.js
  database/seeds/002-users.js
  package.json
  schema/mutation.js
  schema/query.js
  schema/types.js
  yarn.lock
Labels: enhancement

#20 Architecture Updates for Mutations/Bug Fixes
  .eslintignore
  .eslintrc.js
  __tests__/credentialModel.test.js
  __tests__/roleModel.test.js
  __tests__/schoolModel.test.js
  __tests__/server.test.js
  __tests__/userModel.test.js
  database/migrations/20190730092822_credentials.js
  jest.config.js
  knexfile.js
  package.json
  schema/mutation.js
  schema/mutations/index.js
  schema/mutations/schoolMutations.js
  schema/mutations/userMutations.js
  schema/queries/index.js
  web3/web3.js
  yarn.lock
Labels: bug, enhancement

#23 Merge Web3 Refactors, Eslinting, and Jest Config into Master
  .eslintignore
  .eslintrc.js
  __tests__/credentialModel.test.js
  __tests__/roleModel.test.js
  __tests__/schoolModel.test.js
  __tests__/server.test.js
  __tests__/userModel.test.js
  api/auth.js
  api/getDecoded.js
  api/getLoginStatus.js
  api/middleware.js
  api/server.js
  database/migrations/20190730092043_roles.js
  database/migrations/20190730092331_users.js
  database/migrations/20190730092813_schoolDetails.js
  database/migrations/20190730092822_credentials.js
  database/seeds/001-roles.js
  database/seeds/002-users.js
  database/seeds/003-schoolDetails.js
  database/seeds/004-credentials.js
  index.js
  jest.config.js
  knexfile.js
  models/credentialModel.js
  models/roleModel.js
  models/schoolModel.js
  models/userModel.js
  package.json
  schema/mutation.js
  schema/mutations/index.js
  schema/mutations/schoolMutations.js
  schema/mutations/userMutations.js
  schema/queries/index.js
  schema/query.js
  schema/schema.js
  schema/types.js
  web3/web3.js
  yarn.lock
Labels: enhancement, good first issue

#32 Merge Development Work into Master Branch
  __tests__/query.test.js
  __tests__/server.test.js
  database/seeds/002-users.js
  database/seeds/003-schoolDetails.js
  database/seeds/004-credentials.js
  jest.config.js
  knexfile.js
  package.json
  schema/mutation.js
  schema/query.js
  web3/web3.js
  yarn.lock
Labels: enhancement

#37 Invalidate mutation
  schema/mutation.js
  schema/query.js
Labels: enhancement

#38 Readme
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  app.json
  assets/readme-header.png
  database/seeds/002-users.js
  database/seeds/003-schoolDetails.js
  database/seeds/004-credentials.js
  package.json
Labels: documentation

#40 Development
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  __tests__/query.test.js
  app.json
  assets/readme-header.png
  database/migrations/20190730092822_credentials.js
  database/seeds/002-users.js
  database/seeds/003-schoolDetails.js
  database/seeds/004-credentials.js
  package.json
  schema/mutation.js
  schema/query.js
  schema/types.js
Labels: documentation, enhancement

#46 Merge Updated Readme Sections with Development
  README.md
  database/seeds/004-credentials.js
Labels: documentation, enhancement

#47 Merge Current Development Branch Changes with Master
  README.md
  database/seeds/003-schoolDetails.js
  database/seeds/004-credentials.js
Labels: documentation, enhancement

#71 Merge Development with Master Branch
  __tests__/credentialModel.test.js
  __tests__/roleModel.test.js
  __tests__/schoolModel.test.js
  __tests__/schoolMutations.test.js
  __tests__/studentModel.test.js
  __tests__/studentMutations.test.js
  __tests__/userEmailsModel.test.js
  __tests__/userModel.test.js
  __tests__/userMutations.test.js
  database/migrations/20190814154239_userEmails.js
  database/seeds/002-users.js
  database/seeds/006-userEmails.js
  package.json
  schema/mutations/studentMutations.js
  schema/types.js
Labels: enhancement

#74 Merge Additional Bug Fixes for Add Email into Development
  schema/mutations/userMutations.js
  schema/types.js
Labels: bug
